/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     HelloJNI
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_HelloJNI_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     HelloJNI
 * Method:    setDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_HelloJNI_setDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     HelloJNI
 * Method:    getByteArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_HelloJNI_getByteArray
  (JNIEnv *, jobject);

/*
 * Class:     HelloJNI
 * Method:    callToC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_callToC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
